### ISSUE TITLE
Allow AACookieKey/AAHeaderKey to read from a file (e.g. with file:// syntax)

### ISSUE THREAD

**Issue by jw35** [cambridgeuniversity/mod_ucam_webauth#10]
RAVEN096 in master TODO list

**Comment by jw35** [comment]
This would avoid having to put secrets into the Apache configuration where they are prone to leak.

**Comment by mgkuhn** [comment]
I have a prototype of this working and (after a bit more testing and polishing) hope to send a pull request soon.

**Comment by jw35** [comment]
Does it read the keys once at server startup (which would be ideal, though it would require a server restart as and when the keys change), or on every request? The latter will be inefficient, but probably not unacceptably so.

**Comment by mgkuhn** [comment]
It reads the key file only once at startup for `AACookieKey file:...` in `apache2.conf`, but it would read it for each GET request if there is a `AACookieKey file:...` in the relevant `.htaccess` file. This is the first reason for why I do not allow this mechanism from `.htaccess`. Another reason for not allowing `AACookieKey file:...` in `.htaccess` is that this could be abused by someone who has control over a `.htaccess` file to test the content of any file readable to the euid of the Apache process, i.e. it could leak confidential information from the file system.
